### ISSUE TITLE
Use the default UA outline style

### ISSUE THREAD

**Issue by equinusocio** [n-elements/core#165]
We should drop custom outline and use the default UA style. The below snippet enable this on all modern browsers.

```css
*:focus {
  outline: 5px auto Highlight;
  outline: 5px auto -webkit-focus-ring-color;
}
```
